rework htcacheclean integration
* split into separate init script
* activate/deactivate with a2enmod/a2dismo cache_disk
* don't run as root
* add test

diff --git a/debian/apache2.postinst b/debian/apache2.postinst
--- a/debian/apache2.postinst
+++ b/debian/apache2.postinst
@@ -111,6 +111,41 @@ refresh_modules()
 	fi
 }
 
+start_htcacheclean ()
+{
+	local action
+	if [ -x "/etc/init.d/apache-htcacheclean" ]; then
+		if [ -n "$2" ]; then
+			action=restart
+		else
+			action=start
+		fi
+		invoke-rc.d apache-htcacheclean $action || true
+	fi
+}
+
+# The apache-htcacheclean service is disabled by default. Can't use
+# debhelper. The update-rc.d 'enable' call must come after the 'defaults'
+# call, or the former will fail.
+handle_htcacheclean ()
+{
+	if [ -x "/etc/init.d/apache-htcacheclean" ]; then
+		update-rc.d apache-htcacheclean defaults >/dev/null
+	fi
+
+	if dpkg --compare-versions "$2" gt "2.4.18-2~" ||
+	   [ ! -e "/etc/apache2/mods-enabled/cache_disk.load" ] ; then
+		return 0
+	fi
+	if ( . /etc/default/apache-htcacheclean &&
+		[ "$HTCACHECLEAN_MODE" != "cron" ] &&
+		[ "$HTCACHECLEAN_RUN" != "no" ] )
+	then
+		update-rc.d apache-htcacheclean enable 2 3 4 5
+	fi
+	start_htcacheclean
+}
+
 msg ()
 {
 	local PRIORITY="$1"
@@ -191,11 +226,16 @@ case "$1" in
 		enable_default_modules $@
 		enable_default_conf $@
 		install_default_site $@
+		handle_htcacheclean $@
 		execute_deferred_actions
 
 	;;
 
-	abort-upgrade|abort-remove|abort-deconfigure)
+	abort-upgrade)
+		start_htcacheclean $@
+	;;
+
+	abort-remove|abort-deconfigure)
 
 	;;
 
