ask-for-passphrase: bug fixes
- systemd cannot cope with a newline in the prompt, giving this error:

  [/run/systemd/ask-password/ask.RrrIbU:7] Missing '='.
  Failed to parse password file /run/systemd/ask-password/ask.RrrIbU:
  Bad message
  Failed to show password: Bad message

- print newline when not using systemd / plymouth

- remove broken handling for case where stdin is already a tty

diff --git a/debian/ask-for-passphrase b/debian/ask-for-passphrase
--- a/debian/ask-for-passphrase
+++ b/debian/ask-for-passphrase
@@ -21,27 +21,28 @@
 sitename=$1
 keytype=$2
 
-prompt="Apache needs to decrypt your SSL Keys for $sitename ($keytype)
-Please enter passphrase:"
-tty=`tty`
+log="logger -p daemon.err -t apache2"
+
+prompt="Enter passphrase for SSL/TLS keys for $sitename ($keytype):"
+
+# Apache gives us a pipe for stdin, but we want to
+# talk to apache's terminal.
+tty=`tty < /proc/${PPID}/fd/0`
 if [ "$tty" = "not a tty" ] ; then
-    # Apache gives us a pipe for stdin, but we want to
-    # talk to apache's terminal.
-    tty=`tty < /proc/${PPID}/fd/0`
-    if [ "$tty" = "not a tty" ] ; then
-        if [ -x /bin/systemd-ask-password ] ; then
-            exec /bin/systemd-ask-password --timeout=0 "$prompt"
-        elif [ -x /bin/plymouth ] && plymouth --ping ; then
-            echo $prompt | logger
-            exec plymouth ask-for-password --prompt="$prompt"
-        else
-            logger -p daemon.err -t apache2 "No way to ask user for passphrase"
-            exit 1
-        fi
-        logger -p daemon.err -t apache2 "Passphrase prompt failed"
-        exit 1
-    fi
-    # We must not print anything on stdout except the passphrase
-    read -s -p "$prompt" passphrase > $tty 2>&1 < $tty
-    echo "$passphrase"
+	if [ -x /bin/systemd-ask-password ] ; then
+		exec /bin/systemd-ask-password --timeout=0 "$prompt"
+	elif [ -x /bin/plymouth ] && plymouth --ping ; then
+		echo $prompt | logger
+		exec plymouth ask-for-password --prompt="$prompt"
+	else
+		$log "No way to ask user for passphrase"
+		exit 1
+	fi
+	$log "Passphrase prompt failed"
+	exit 1
 fi
+
+# We must not print anything on stdout except the passphrase
+read -s -p "$prompt" passphrase > $tty 2>&1 < $tty
+echo > $tty
+echo "$passphrase"
