Allow the use of apache2-maintscript-helper from a sub-function. We rely on dpkg's arguments supplied in $1, $2 etc. This clashes with function arguments supplied to to sh sub-function. Allow manual override in such cases.

diff --git a/debian/debhelper/apache2-maintscript-helper b/debian/debhelper/apache2-maintscript-helper
--- a/debian/debhelper/apache2-maintscript-helper
+++ b/debian/debhelper/apache2-maintscript-helper
@@ -49,7 +49,13 @@
 #				dpkg supplies to maintainer scripts and similar
 #				information. These variables are an
 #				implementation detail and not to be changed.
-
+#
+#				You might want to set them manually only if you
+#				are calling apache2-maintscript-helper from
+#				some place which does not preserve the original
+#				script arguments for example when calling from
+#				a subfunction instead of the main function in
+#				your maintainer script
 
 #
 # INITIALIZATION
@@ -94,8 +100,25 @@ else
 		APACHE2_MAINTSCRIPT_PACKAGE="${APACHE2_MAINTSCRIPT_PACKAGE%.*}"
 	fi
 
-	APACHE2_MAINTSCRIPT_METHOD="$1"
-	APACHE2_MAINTSCRIPT_ARGUMENT="${2:-}"
+	if [ -z "$APACHE2_MAINTSCRIPT_METHOD" ] ; then
+		APACHE2_MAINTSCRIPT_METHOD="$1"
+	fi
+
+	case "$APACHE2_MAINTSCRIPT_METHOD" in
+		install|upgrade|abort-upgrade|configure|abort-remove|abort-remove|abort-deconfigure|remove|failed-upgrade|purge|disappear|abort-install)
+			# yay - recognized script
+		;;
+		*)
+			echo "apache2-maintscript-helper invoked from a modified environment. Please hint required arguments manually" >&2
+			return 1
+		;;
+	esac
+
+
+
+	if [ -z "$APACHE2_MAINTSCRIPT_ARGUMENT" ] ; then
+		APACHE2_MAINTSCRIPT_ARGUMENT="${2:-}"
+	fi
 
 fi
 
